"""Generate site/index.html from challenge metadata and preview images."""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = os.path.join(ROOT, "site")
OUT = os.path.join(SITE, "index.html")


def blurb(path):
    with open(path, encoding="utf-8") as f:
        text = f.read()
        for line in text.splitlines():
            line = line.strip()
            if line and not line.startswith(("#", ">", "-", "|", "[", "*", "\n")):
                return re.sub(r"\*\*", "", line).strip()
    return ""


CHALLENGES = [
    {
        "dir": "01-projectile",
        "title_en": "Projectile Motion",
        "title_zh": "抛体运动",
        "tag_en": "Classical Mechanics",
        "tag_zh": "经典力学",
    },
    {
        "dir": "02-pendulum",
        "title_en": "Pendulum",
        "title_zh": "单摆",
        "tag_en": "Numerical Methods",
        "tag_zh": "数值方法",
    },
    {
        "dir": "03-orbit",
        "title_en": "Orbit",
        "title_zh": "轨道",
        "tag_en": "Gravitation",
        "tag_zh": "万有引力",
    },
    {
        "dir": "04-nbody",
        "title_en": "N-Body",
        "title_zh": "N 体",
        "tag_en": "Many-Body Systems",
        "tag_zh": "多体系统",
    },
    {
        "dir": "05-wave-machine",
        "title_en": "Wave Machine",
        "title_zh": "波",
        "tag_en": "Waves",
        "tag_zh": "波动",
    },
    {
        "dir": "06-heat-engine",
        "title_en": "Heat Engine",
        "title_zh": "热机",
        "tag_en": "Thermodynamics",
        "tag_zh": "热力学",
    },
    {
        "dir": "07-double-pendulum",
        "title_en": "Double Pendulum",
        "title_zh": "双摆",
        "tag_en": "Chaos",
        "tag_zh": "混沌",
    },
    {
        "dir": "08-fluid",
        "title_en": "Fluid",
        "title_zh": "流体",
        "tag_en": "CFD",
        "tag_zh": "计算流体力学",
    },
    {
        "dir": "09-electromagnetism",
        "title_en": "Electromagnetism",
        "title_zh": "电磁",
        "tag_en": "Electromagnetism",
        "tag_zh": "电磁学",
    },
    {
        "dir": "10-relativity",
        "title_en": "Relativity",
        "title_zh": "相对论",
        "tag_en": "Special Relativity",
        "tag_zh": "狭义相对论",
    },
    {
        "dir": "11-quantum",
        "title_en": "Quantum",
        "title_zh": "量子",
        "tag_en": "Quantum Mechanics",
        "tag_zh": "量子力学",
    },
    {
        "dir": "12-solar-system",
        "title_en": "Solar System",
        "title_zh": "太阳系",
        "tag_en": "Capstone",
        "tag_zh": "毕业项目",
    },
]

for c in CHALLENGES:
    base = os.path.join(ROOT, "challenges", c["dir"])
    c["num"] = c["dir"].split("-")[0]
    c["blurb_en"] = blurb(os.path.join(base, "README.en.md"))[:150]
    c["blurb_zh"] = blurb(os.path.join(base, "README.md"))[:120]
    c["img"] = f"previews/preview_{int(c['num']):02d}.png"

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Build Your Own Physics</title>
<meta name="description" content="Master physics by recreating it from scratch. 12 hands-on coding challenges from projectile motion to quantum mechanics.">
<link rel="stylesheet" href="styles.css">
</head>
<body>
<header class="site-header">
  <nav class="nav">
    <a class="logo" href="#">Build Your Own Physics</a>
    <div class="nav-right">
      <button id="lang-toggle" class="lang-toggle" aria-label="Toggle language">English / 中文</button>
      <a class="btn" href="https://github.com" target="_blank" rel="noopener">GitHub</a>
    </div>
  </nav>
  <div class="hero">
    <h1 class="lang-en">Master physics by recreating it from scratch.</h1>
    <h1 class="lang-zh">亲手重建物理定律，而不仅仅是背诵它们。</h1>
    <p class="tagline lang-en">12 coding challenges — from projectile motion to quantum mechanics — designed for absolute beginners. AI-assisted, math-explained, fully bilingual.</p>
    <p class="tagline lang-zh">12 个挑战，从抛体运动到量子力学。完全零基础友好，AI 全程辅助，数学即时讲解，中英双语。</p>
    <div class="hero-cta">
      <a class="btn primary" href="#roadmap">Start Challenge 01</a>
      <a class="btn" href="../README.md">Read README</a>
      <a class="btn" href="../README.en.md">English README</a>
    </div>
  </div>
</header>

<main>
<section id="roadmap" class="roadmap">
  <div class="section-header">
    <h2 class="lang-en">The Roadmap</h2>
    <h2 class="lang-zh">挑战路线</h2>
    <p class="lang-en">Each challenge is a self-contained simulation. The previews below are real outputs generated by the reference solutions.</p>
    <p class="lang-zh">每个挑战都是独立的物理模拟。下方预览图全部来自参考实现的实际输出。</p>
  </div>

  <div class="cards">
{CARDS}
  </div>
</section>

<section class="features">
  <div class="feature">
    <h3 class="lang-en">Zero prerequisite</h3>
    <h3 class="lang-zh">零基础起点</h3>
    <p class="lang-en">No calculus, no physics background, no prior coding. Start with Challenge 00 · Python Crash Course.</p>
    <p class="lang-zh">不需要微积分、不需要物理背景、不需要编程基础。从「挑战 00 · Python 零基础速成」开始。</p>
  </div>
  <div class="feature">
    <h3 class="lang-en">Reconstructive learning</h3>
    <h3 class="lang-zh">重构式学习</h3>
    <p class="lang-en">"What I cannot create, I do not understand." Every formula is rebuilt in code before it is memorized.</p>
    <p class="lang-zh">「凡我不能创造的，我就尚未理解。」每个公式先在代码里重建，再装进脑袋。</p>
  </div>
  <div class="feature">
    <h3 class="lang-en">Automated grading</h3>
    <h3 class="lang-zh">自动评分</h3>
    <p class="lang-en">Each challenge ships with a SPEC and a verify script, wired into GitHub Actions for instant feedback.</p>
    <p class="lang-zh">每个挑战都包含 SPEC 与验证脚本，并接入 GitHub Actions，提交即得反馈。</p>
  </div>
</section>
</main>

<footer class="site-footer">
  <p class="lang-en">Released under the MIT License · Built for learners who want to understand physics by creating it.</p>
  <p class="lang-zh">MIT 协议开源 · 献给所有想通过创造来理解物理的学习者。</p>
</footer>

<script>
(function() {{
  const btn = document.getElementById('lang-toggle');
  const html = document.documentElement;
  let current = 'en';
  function setLang(lang) {{
    current = lang;
    html.lang = lang === 'en' ? 'en' : 'zh-CN';
    document.body.classList.toggle('zh-mode', lang === 'zh');
  }}
  btn.addEventListener('click', function() {{
    setLang(current === 'en' ? 'zh' : 'en');
  }});
}})();
</script>
</body>
</html>
"""

card_html = []
for c in CHALLENGES:
    card_html.append(f"""    <article class="card">
      <a class="card-img" href="../challenges/{c['dir']}/README.md">
        <img src="{c['img']}" alt="Challenge {c['num']} preview" loading="lazy">
      </a>
      <div class="card-body">
        <div class="card-meta">
          <span class="badge num">{c['num']}</span>
          <span class="badge tag lang-en">{c['tag_en']}</span>
          <span class="badge tag lang-zh">{c['tag_zh']}</span>
        </div>
        <h3 class="card-title">
          <span class="lang-en">{c['title_en']}</span>
          <span class="lang-zh">{c['title_zh']}</span>
        </h3>
        <p class="card-desc lang-en">{c['blurb_en']}</p>
        <p class="card-desc lang-zh">{c['blurb_zh']}</p>
        <div class="card-links">
          <a href="../challenges/{c['dir']}/README.md">中文</a>
          <a href="../challenges/{c['dir']}/README.en.md">English</a>
          <a href="../challenges/{c['dir']}/SPEC.md">SPEC</a>
          <a href="../challenges/{c['dir']}/SPEC.en.md">SPEC.en</a>
        </div>
      </div>
    </article>""")

html = TEMPLATE.format(CARDS="\n".join(card_html))
with open(OUT, "w", encoding="utf-8") as f:
    f.write(html)

print(f"Wrote {OUT}")
